import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
// const About = React.lazy(() => import('../components/About'));
import About from '../components/About';
import Main from '../components/Main';
import Navbar from '../components/Navbar';
import Skills from '../components/Skills';
import PersonalProjects from '../components/PersonalProjects';
import Contact from '../components/Contact';
import { Toaster } from 'react-hot-toast';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ely Fuentes | Software Engineer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Toaster position="bottom-right" toastOptions={{duration: 3000}} />
      <Navbar />
      <Main />
      <About />
      <Skills />
      <PersonalProjects />
      <Contact />
    </div>
  );
}
