import React, { Suspense } from 'react';
import Head from 'next/head';
import Image from 'next/image';
const About = React.lazy(() => import('../components/About'));
// import About from '../components/About';
import Main from '../components/Main';
import Navbar from '../components/Navbar';
import Skills from '../components/Skills';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ely Fuentes | Software Engineer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
    </div>
  );
}
